import Link from "next/link";
import Script from "next/script";
import "./App.css";
import "./index.css";
import Logo from "./assets/logo.png";
import Image from "next/image";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="container-fluid">
          <div className="header">
            <div className="logo">
              <Link href="/">
              <Image src={Logo} alt="logo" className="logo" /></Link>
            </div>
            <ul className="menu">
              <Link href="/blog">Nested</Link>
              <Link href="/products">Dynamic</Link>
              <li>
                <a href="/login">Group</a>
              </li>
              <li>
                <a href="/parallel">Parallel</a>
              </li>
              <li>
                <a href="/interceptor">Interceptor</a>
              </li>
            </ul>
          </div>
        </div>
        {children}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    ></link>
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
          crossOrigin="anonymous"
        ></Script>
      </body>
    </html>
  );
}
